-- V018: Dados de demonstração para módulo PGV (req 219) — removida.
-- Setor de cálculo de PoC (dados fictícios) não deve mais ser semeado em
-- bancos novos. Setores reais são cadastrados via POST /pgv/setores.
